### ISSUE TITLE
Add ability to reset ability score selection

### ISSUE THREAD

**Issue by ItsDrafty** [koboldpress/black-flag#491]
Hello, 

I might have just missed a way on how to do this. But I noticed there is no way to remove a class from the progression page once you've added one. Didn't see a trash bin icon next to it like heritage/lineage has. Also, there does not appear to be a way to alter your ability score distribution once you've chosen one. If you make a mistake choosing your ability score method or choice and need to change, this could be an issue if you built out your character already and would have to start again.

Keep up the great work!
Thanks!

**Comment by arbron** [comment]
Classes can be removed by going into edit mode and using the "Level Down" button next to the most recent level. There is no way to delete a class all at once because of the way levels are tracked so you just level down until there are no more levels of that class and it will be removed.

You can manually set ability scores after the fact if the system setting is set to allow it, but there is no way at the moment to totally reset the process. That should be added.

**Comment by ItsDrafty** [comment]
Ah! Okay that explains it. I thought that arrow with bars was for sorting. Maybe a different icon in the future?

Anyways, thanks for all the hard work!
